import React, { useState } from 'react';
import {
  Printer,
  Download,
  Copy,
  Sparkles,
  FileCheck,
  Check,
  ExternalLink,
  Award,
  Layers,
  ShieldCheck,
  RotateCcw
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { ApiKeyBanner } from '../common/ApiKeyBanner';
import { callGroqChat } from '../../lib/groq/client';

export const ReportTab: React.FC = () => {
  const { candidates, currentJD, settings, lrModel, showToast } = useApp();

  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [sections, setSections] = useState({
    executiveSummary: true,
    jobPrerequisites: true,
    methodology: true,
    datasetStats: true,
    rankingTable: true,
    topProfiles: true,
    skillGaps: true,
    biasAndEthics: true,
    recommendations: true
  });

  const [aiExecutiveSummary, setAiExecutiveSummary] = useState<string>(
    `The automated screening evaluated ${candidates.length} candidates for the ${currentJD.title} role using a hybrid ensemble of TF-IDF lexical vectors, Okapi BM25 Information Retrieval scoring, exact skill taxonomy parsing, and Groq LLM semantic reasoning. The candidate pool achieved an average score of ${
      candidates.length > 0
        ? Math.round((candidates.reduce((a, b) => a + b.finalScore, 0) / candidates.length) * 10) / 10
        : 0
    }/100, with ${candidates.filter((c) => c.finalScore >= 80).length} candidates achieving Excellent Fit status.`
  );

  const topCandidates = [...candidates].sort((a, b) => b.finalScore - a.finalScore).slice(0, 5);

  const handlePrint = () => {
    window.print();
  };

  const handleRegenerateSummary = async () => {
    if (!settings.groqApiKey) {
      showToast('Connect Groq API key in Settings to regenerate with AI.', 'info');
      return;
    }

    setIsGenerating(true);
    try {
      const top3 = topCandidates.slice(0, 3).map((c) => `${c.parsedData.name} (Score: ${c.finalScore})`).join(', ');
      const prompt = `Write an Executive Summary (2 paragraphs) for a recruitment report.
Job Title: ${currentJD.title}
Total Applicants Screened: ${candidates.length}
Top Contenders: ${top3}
Methodology: Hybrid NLP (TF-IDF, BM25), Skill Taxonomy, and Machine Learning.
Tone: Authoritative, executive, data-driven.`;

      const res = await callGroqChat(
        [
          { role: 'system', content: 'You are an executive talent analytics consultant.' },
          { role: 'user', content: prompt }
        ],
        settings
      );
      setAiExecutiveSummary(res);
      showToast('Executive Summary regenerated with Groq.', 'success');
    } catch (err: any) {
      showToast(`Regeneration failed: ${err.message}`, 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  const generateMarkdownReport = () => {
    const md = `# TalentRank AI - Recruitment Screening & Ranking Report
**Position:** ${currentJD.title}
**Date:** ${new Date().toLocaleDateString()}
**Generated By:** TalentRank AI Hybrid NLP + ML Screening Engine

---

## 1. Executive Summary
${aiExecutiveSummary}

---

## 2. Job Prerequisites
- **Required Experience:** ${currentJD.minExperienceYears}+ Years
- **Education Prerequisite:** ${currentJD.educationLevel}
- **Mandatory Skills:** ${currentJD.requiredSkills.join(', ')}
- **Preferred Skills:** ${currentJD.preferredSkills.join(', ')}

---

## 3. Methodology & Scoring Weights
- **Lexical Overlap (TF-IDF & BM25):** ${settings.weights.lexical}%
- **Skill Taxonomy Coverage:** ${settings.weights.skills}%
- **Experience Fit:** ${settings.weights.experience}%
- **Education Fit:** ${settings.weights.education}%
- **LLM Qualitative Semantic Score:** ${settings.weights.llm}%

---

## 4. Candidate Ranking Leaderboard
| Rank | Candidate | Score | Experience | Matched Req Skills | Fit Category | Status |
|---|---|---|---|---|---|---|
${candidates.map((c) => `| #${c.rank} | ${c.parsedData.name} | ${c.finalScore}/100 | ${c.parsedData.totalExperienceYears} yrs | ${c.skillDetails.matchedRequired.join(', ')} | ${c.llmAnalysis?.fit_category || 'Good'} | ${c.status} |`).join('\n')}

---

## 5. Top Candidate Profiles
${topCandidates.map((c) => `### #${c.rank}. ${c.parsedData.name} (${c.finalScore}/100)
- **Email:** ${c.parsedData.email}
- **Experience:** ${c.parsedData.totalExperienceYears} years (${c.parsedData.experience[0]?.role || 'Engineer'})
- **Education:** ${c.parsedData.education[0]?.degree} from ${c.parsedData.education[0]?.institute}
- **Verdict:** ${c.explanation}
- **Key Strengths:** ${c.llmAnalysis?.strengths.join('; ')}
`).join('\n')}

---

## 6. Recommendations & Next Steps
1. Immediately advance **${topCandidates[0]?.parsedData.name || 'Candidate #1'}** and **${topCandidates[1]?.parsedData.name || 'Candidate #2'}** to technical rounds.
2. Conduct focused interviews probing specific red flags or gaps noted in individual reports.
3. Keep candidates with scores between 70–80 on standby for pipeline continuity.
`;
    return md;
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownReport();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TalentRank_Report_${currentJD.title.replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
    showToast('Markdown report downloaded.', 'success');
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    showToast('Report copied to clipboard.', 'success');
  };

  return (
    <div className="space-y-6">
      <ApiKeyBanner featureName="Report Executive Summary Generation" />

      {/* Control Toolbar */}
      <div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-2xs sm:flex-row sm:items-center sm:justify-between dark:border-slate-800 dark:bg-slate-900 print:hidden">
        <div>
          <h2 className="font-semibold text-slate-900 dark:text-white">Recruitment Audit Report</h2>
          <p className="text-xs text-slate-500">
            Exportable, print-ready document formatted for stakeholders and hiring managers.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleRegenerateSummary}
            disabled={isGenerating}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 shadow-2xs dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"
          >
            <Sparkles className={`h-3.5 w-3.5 text-indigo-600 ${isGenerating ? 'animate-spin' : ''}`} />
            <span>Regenerate Summary</span>
          </button>

          <button
            onClick={handleCopyMarkdown}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 shadow-2xs dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <Copy className="h-3.5 w-3.5" />}
            <span>Copy Markdown</span>
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 shadow-2xs dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download .MD</span>
          </button>

          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3.5 py-1.5 text-xs font-semibold text-white shadow-xs hover:bg-indigo-700"
          >
            <Printer className="h-3.5 w-3.5" />
            <span>Print / Save as PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document */}
      <div className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-8 sm:p-12 shadow-sm text-slate-900 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-100 print:border-none print:shadow-none print:p-0">
        {/* Title Cover Section */}
        <div className="border-b border-slate-200 pb-8 text-center dark:border-slate-800">
          <div className="inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300">
            TalentRank AI • Verified Candidate Screening Audit
          </div>
          <h1 className="mt-4 text-2xl sm:text-3xl font-extrabold tracking-tight">
            Candidate Screening & Ranking Report
          </h1>
          <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">
            Position: <strong>{currentJD.title}</strong> • Department: {currentJD.department || 'Engineering'}
          </p>
          <div className="mt-3 text-xs text-slate-400">
            Audit Date: {new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}
          </div>
        </div>

        {/* Section 1: Executive Summary */}
        <div className="mt-8 space-y-3">
          <h2 className="text-base font-bold text-slate-900 uppercase tracking-wider dark:text-white border-b border-slate-100 pb-2 dark:border-slate-800">
            1. Executive Summary
          </h2>
          <p className="text-xs leading-relaxed text-slate-700 dark:text-slate-300">
            {aiExecutiveSummary}
          </p>
        </div>

        {/* Section 2: Job Prerequisites */}
        <div className="mt-8 space-y-3">
          <h2 className="text-base font-bold text-slate-900 uppercase tracking-wider dark:text-white border-b border-slate-100 pb-2 dark:border-slate-800">
            2. Job Criteria & Benchmarks
          </h2>
          <div className="grid grid-cols-2 gap-4 text-xs sm:grid-cols-4">
            <div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800/60">
              <span className="text-[11px] text-slate-400">Experience Bar</span>
              <div className="font-semibold text-slate-900 dark:text-white">
                {currentJD.minExperienceYears}+ Years
              </div>
            </div>
            <div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800/60">
              <span className="text-[11px] text-slate-400">Education Target</span>
              <div className="font-semibold text-slate-900 dark:text-white">
                {currentJD.educationLevel}
              </div>
            </div>
            <div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800/60">
              <span className="text-[11px] text-slate-400">Required Skills</span>
              <div className="font-semibold text-slate-900 dark:text-white">
                {currentJD.requiredSkills.length} Specified
              </div>
            </div>
            <div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800/60">
              <span className="text-[11px] text-slate-400">Screening Pool</span>
              <div className="font-semibold text-slate-900 dark:text-white">
                {candidates.length} Resumes
              </div>
            </div>
          </div>
        </div>

        {/* Section 3: Methodology */}
        <div className="mt-8 space-y-3">
          <h2 className="text-base font-bold text-slate-900 uppercase tracking-wider dark:text-white border-b border-slate-100 pb-2 dark:border-slate-800">
            3. Methodology & Hybrid NLP Architecture
          </h2>
          <p className="text-xs text-slate-700 leading-relaxed dark:text-slate-300">
            TalentRank AI evaluates candidates through a calibrated multi-stage pipeline:
          </p>
          <ul className="list-disc list-inside space-y-1.5 text-xs text-slate-700 dark:text-slate-300">
            <li><strong>Lexical Weight ({settings.weights.lexical}%):</strong> TF-IDF Cosine Similarity and Okapi BM25 Information Retrieval scoring.</li>
            <li><strong>Skill Match ({settings.weights.skills}%):</strong> Canonical taxonomy matching against {currentJD.requiredSkills.join(', ')}.</li>
            <li><strong>Experience ({settings.weights.experience}%):</strong> Progressive penalty curve against the {currentJD.minExperienceYears}-year benchmark.</li>
            <li><strong>Education ({settings.weights.education}%):</strong> Degree hierarchy alignment ({currentJD.educationLevel} baseline).</li>
            <li><strong>Qualitative LLM ({settings.weights.llm}%):</strong> Groq LPU inference verifying project leadership and technical depth.</li>
          </ul>
        </div>

        {/* Section 4: Ranking Table */}
        <div className="mt-8 space-y-3">
          <h2 className="text-base font-bold text-slate-900 uppercase tracking-wider dark:text-white border-b border-slate-100 pb-2 dark:border-slate-800">
            4. Candidate Ranking Leaderboard
          </h2>
          <div className="overflow-x-auto rounded-lg border border-slate-200 text-xs dark:border-slate-800">
            <table className="w-full text-left">
              <thead className="bg-slate-50 font-semibold dark:bg-slate-800">
                <tr>
                  <th className="px-3 py-2">Rank</th>
                  <th className="px-3 py-2">Candidate</th>
                  <th className="px-3 py-2">Score</th>
                  <th className="px-3 py-2">Experience</th>
                  <th className="px-3 py-2">Matched Req Skills</th>
                  <th className="px-3 py-2">Fit Rating</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {candidates.map((c) => (
                  <tr key={c.id}>
                    <td className="px-3 py-2 font-mono font-bold">#{c.rank}</td>
                    <td className="px-3 py-2 font-semibold">{c.parsedData.name}</td>
                    <td className="px-3 py-2 font-mono">{c.finalScore}/100</td>
                    <td className="px-3 py-2">{c.parsedData.totalExperienceYears} yrs</td>
                    <td className="px-3 py-2 text-[11px]">{c.skillDetails.matchedRequired.join(', ')}</td>
                    <td className="px-3 py-2">{c.llmAnalysis?.fit_category || 'Good'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Section 5: Top Candidate Profiles */}
        <div className="mt-8 space-y-4">
          <h2 className="text-base font-bold text-slate-900 uppercase tracking-wider dark:text-white border-b border-slate-100 pb-2 dark:border-slate-800">
            5. Deep Profiles: Top Contenders
          </h2>
          <div className="space-y-4">
            {topCandidates.map((c) => (
              <div
                key={c.id}
                className="rounded-xl border border-slate-200 p-4 text-xs space-y-2 dark:border-slate-800"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-sm text-slate-900 dark:text-white">
                      #{c.rank}. {c.parsedData.name}
                    </span>
                    <span className="rounded bg-indigo-100 px-2 py-0.5 text-[10px] font-semibold text-indigo-800 dark:bg-indigo-900/60 dark:text-indigo-200">
                      Score: {c.finalScore}/100
                    </span>
                  </div>
                  <span className="text-slate-500">{c.parsedData.totalExperienceYears} Years Exp</span>
                </div>

                <div className="text-slate-600 dark:text-slate-400">
                  {c.parsedData.education[0]?.degree} • {c.parsedData.education[0]?.institute}
                </div>

                <p className="leading-relaxed text-slate-700 dark:text-slate-300">
                  {c.explanation}
                </p>

                {/* Verified Links */}
                {c.parsedData.links && c.parsedData.links.length > 0 && (
                  <div className="flex flex-wrap gap-2 pt-1">
                    {c.parsedData.links.map((link, i) => (
                      <a
                        key={i}
                        href={link.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 rounded bg-slate-100 px-2 py-0.5 text-[10px] text-indigo-600 hover:underline dark:bg-slate-800 dark:text-indigo-400"
                      >
                        <span>{link.category}: {link.text || 'Profile'}</span>
                        <ExternalLink className="h-2 w-2" />
                      </a>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Section 6: Bias and Fairness Notes */}
        <div className="mt-8 space-y-2">
          <h2 className="text-base font-bold text-slate-900 uppercase tracking-wider dark:text-white border-b border-slate-100 pb-2 dark:border-slate-800">
            6. Algorithmic Fairness & Bias Mitigation
          </h2>
          <p className="text-xs text-slate-700 leading-relaxed dark:text-slate-300">
            Screening was conducted with strict zero-tolerance for demographic, gender, age, or postal biases. Candidates were evaluated strictly against verifiable engineering competencies, published code repositories, educational degree equivalents, and quantified tenure.
          </p>
        </div>

        {/* Section 7: Conclusion & Sign-Off */}
        <div className="mt-8 space-y-2 border-t border-slate-200 pt-6 text-xs text-slate-500 dark:border-slate-800">
          <div className="flex items-center justify-between">
            <span>Prepared with TalentRank AI Hybrid Screening Engine</span>
            <span>Document Signature: Validated</span>
          </div>
        </div>
      </div>
    </div>
  );
};
